name: simplecashier
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.2
  blue_print_pos: ^0.0.14
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_messaging: ^14.0.3
  firebase_storage: ^11.0.3
  flutter_local_notifications: ^12.0.3
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_neumorphic: ^3.2.0
  fluttertoast: ^8.1.1
  image: ^3.2.2
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.1
  path_provider: ^2.0.11
  pinput: ^2.2.16
  provider: ^6.0.4
  screenshot: ^1.2.3
  shared_preferences: ^2.0.15
  shimmer_animation: ^2.1.0+1
  uuid: ^3.0.6
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
    - assets/audios/
