name: simplecashier
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.0.3
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.2
  firebase_auth: ^4.1.0
  firebase_core_web: ^2.0.1
  firebase_messaging: ^14.0.3
  firebase_storage: ^11.0.3
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_local_notifications: ^12.0.3
  flutter_neumorphic: ^3.2.0
  fluttertoast: ^8.1.1
  intl_phone_number_input: ^0.7.1
  meta: ^1.8.0
  path_provider: ^2.0.11
  pdf: ^3.8.4
  printing: ^5.9.3
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  shimmer_animation: ^2.1.0+1
  uuid: ^3.0.6
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
    - assets/audios/
    - assets/fonts/
