name: simplecashier
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
