name: simplecashier
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  easy_localization: any
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  provider: ^6.0.3
  screenshot: ^1.2.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
