name: simplecashier
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cached_network_image: ^3.2.2
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.10+1
  easy_localization: any
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_storage: ^10.3.8
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  screenshot: ^1.2.3
  another_flushbar: ^1.12.29
  
  uuid: ^3.0.6
  # flutter_native_splash-development.yaml
   
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  background_image: assets/images/bg.png
  

  android_12:
    color: "#ffffff"
    image: assets/images/logo.png
    background_image: assets/images/bg.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

  # web: true

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/
